version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Clone docs
          working_directory: ~/workdir
          command: |
            git remote add origin https://github.com/banasik/githubTest.git
            git push -u origin master