version: 2
jobs:
  build:
    
    # The base environment we'll use (can be any docker image w/ git)
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      # Move the repository code to our home directory in the CircleCI build
      - checkout
      
      

      # Add the mirror repository as a git remote
      - run: 
         git push -u https://github.com/banasik/githubTest.git master      
