version: 2
jobs:
  build:
    
    # The base environment we'll use (can be any docker image w/ git)
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      # Move the repository code to our home directory in the CircleCI build
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 00:7e:e5:d6:2f:f5:dd:ad:94:73:04:f5:ca:fa:3b:60
      
      

      # Add the mirror repository as a git remote
      - run: 
         git push -u ssh git@github.com:banasik/githubTest.git master      
