version: 2
jobs:
  build:
    
    # The base environment we'll use (can be any docker image w/ git)
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - run: 
         git pull martinbanasik-bs@bitbucket.org:martinbanasik-bs/bitbuckettest.git
         git push https://banasik:marban28@github.com/banasik/githubTest.git