version: 2

jobs:

    synrepos:

        working_directory: ~/repo

        docker:

            - image: circleci/ruby:2.4.1-jessie
        steps:
            - checkout
            - run:
                name: syn bb to github
                command: |

                    git remote add origin https://github.com/banasik/githubTest.git
                    git push -u origin master